// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjhhndfmxhsbjjbbrxbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaGhuZGZteGhzYmpqYmJyeGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzI3MzQsImV4cCI6MjA2ODQ0ODczNH0.t2jc8s5qAWY__uHM_riHBumoicdzwHYkwF_KKXzVmEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});